name: Running Unit Tests

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: macos-latest
    
    steps:
    - name: Compile code
      run: |
        g++ main.cpp -I/opt/homebrew/Cellar/sfml/2.6.1/include -o main -L/opt/homebrew/Cellar/sfml/2.6.1/lib -lsfml-graphics -lsfml-window -lsfml-system
      
