name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SFML
      run: brew install sfml
    - name: Compile main.cpp
      run: g++ main.cpp -I/opt/homebrew/Cellar/sfml/2.6.1/include -o main -L/opt/homebrew/Cellar/sfml/2.6.1/lib -lsfml-graphics -lsfml-window -lsfml-system
    - name: Compile unit tests
      run: g++ runTest.cpp -o runTest
    - name: Run unit tests
      run: ./runTest
