name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SFML
      run: brew install sfml
    - name: Compile main.cpp
      run: make
    - name: Compile unit tests
      run: g++ runTest.cpp -o runTest
    - name: Run unit tests
      run: ./runTest
